# Generated by Django 4.2.3 on 2023-08-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_course_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
    ]
