# Generated by Django 4.2.3 on 2023-08-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
